word_list = {
    "apple": "яблоко",
    "book": "книга",
    "cat": "кошка",
    "dog": "собака",
    "elephant": "слон",
    "family": "семья",
    "green": "зеленый",
    "house": "дом",
    "ice": "лед",
    "journey": "путешествие",
    "key": "ключ",
    "language": "язык",
    "mountain": "гора",
    "nature": "природа",
    "ocean": "океан",
    "paper": "бумага",
    "question": "вопрос",
    "river": "река",
    "sun": "солнце",
    "tree": "дерево",
    "umbrella": "зонт",
    "victory": "победа",
    "weather": "погода",
    "yellow": "желтый",
    "zoo": "зоопарк"
}